# Generated by Django 5.1.4 on 2025-01-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='converted_to_images',
            field=models.BooleanField(default=False),
        ),
    ]
